export { default as Navbar } from "./navbar/Navbar"
export { default as Footer } from "./footer/Footer"
export { default as BannerSlider } from "./banner/BannerSlider"
export { default as BannerImg } from "./banner/BannerImg"
export { default as AdminNavbar } from "./admin/AdminNavbar"
export { default as AdminSidebar } from "./admin/AdminSidebar"
export { default as HotelNavbar } from "./hotel/HotelNavbar"
export { default as HotelSidebar } from "./hotel/HotelSidebar"